spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 8.129.110.202
  main:
    allow-bean-definition-overriding: true # 允许存在多个Fegin调用相同的Service接口
#server:
#  servlet:
#    context-path: /order
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
# OpenFeign日志管理
logging:
  level:
    crw.team.order.service.remoteService.ProjectService: debug

hystrix:
  metrics:
    polling-interval-ms: 5000
    enabled: true

##########################seata#############################
seata:
  enabled: true
  application-id: seata-server
  tx-service-group: default
  enable-auto-data-source-proxy: true
  use-jdk-proxy: false
  service:
    vgroup-mapping:
      default: seata-server
    enable-degrade: false
    disable-global-transaction: false
  registry:
    type: eureka
    eureka:
      weight: 1
      service-url: http://localhost:7001/eureka/