server:
  port: 8088

spring:
  application:
    name: clock
  datasource:
    # type: com.mysql.cj.jdbc.MysqlDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.129.110.202:3306/ClockSystem?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: hellocrw.1103
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: crw.clock.entity.**
  configuration:
    # 开启SQL日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰名命
    map-underscore-to-camel-case: true

config:
  jwt:
    # 加密密钥
    secret: secret
    # token有效时长，单位秒
    expire: 3600
    # header 名称
    headerKey: token
    token: Authorization