spring:
  application:
    name: session-demos
  redis:
    database: 1
    host: 8.129.110.202
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000
  session:
    store-type: redis

server:
  port: 9092
