server:
  port: 7010

spring:
  application:
    name: nacos-01

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.92.135:8848
    sentinel:
      transport:
        dashboard: 192.168.92.135:8080
        port: 8719
