server:
  port: 9003

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellocrw/teamup-config-center.git
          search-paths:
            - teamup-config-center
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka