server:
  port: 9001
spring:
  application:
    name: team-api-commons
  datasource:
    #    type: com.mysql.cj.jdbc.MysqlDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.129.110.202:3306/team?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: hellocrw.1103
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: crw.commons.entity